---
- name: jenkins installation
  hosts: all
  become: true
  tasks:
  - name: Install java pacakage
    yum:
     name: java-1.8.0-openjdk-devel
     state: latest
    become: true
  - name: Enable the Jenkins repository
    uri:
     url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo | tee /etc/yum.repos.d/jenkins.repo
     method: get
    become: true
  - name: Add key
    rpm_key:
     key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
     state: present
    become: true
  - name: Install jenkins
    yum:
     name: jenkins
     state: present
    become: true
  - name: Start service of jenkins
    service:
     name: jenkins
     state: started
     enabled: true
    become: true 
