---
- name: kubernetes installation with ansible automation
  hosts: all
  become: yes

  tasks:
   - name: network configration
     nmcli:
       con_name: test
       ifname: eth0
       type: ethernet
       state: present
   
   - name: set hostname 
     ansible.builtin.hostname:
       name: "master.example.com"
       become: true   
         
   - name: Configure Kubernetes Repository for centos 7
     shell:
       cat <<EOF > /etc/yum.repos.d/kubernetes.repo
       [kubernetes]
       name=Kubernetes
       baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
       enabled=1
       gpgcheck=1
       repo_gpgcheck=1
       gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
       EOF
     
   - name: Install kubelet, kubeadm, and kubectl
     yum:
       name: kubelet kubeadm kubectl
       state: present
    
   - name: kubelet service start and enable
     service:
       name: kubelet
       state: start
       enabled: yes

   - name: entry in hosts file 
     shell:
       echo "master.example.com" >> /etc/hosts
   
   - name: Configure Firewall
     firewalld:
       port: "{{ item }}"
       permanent: yes
       state: enabled
     loop:
       -6443/tcp
       -2379-2380/tcp
       -10250/tcp
       -10251/tcp
       -10252/tcp
       -10255/tcp
   - name: service reload
     systemd:
       name: firewalld
       state: reloaded
   - name: Update Iptables Settings
     shell:
       cat <<EOF > /etc/sysctl.d/k8s.conf
       net.bridge.bridge-nf-call-ip6tables = 1
       net.bridge.bridge-nf-call-iptables = 1
       EOF
       sysctl --system 
   - name: Disable SELinux
     selinux:
       state: disabled
   - name: Disable SWAP
     shell: 
       sed -i '/swap/d' /etc/fstab
       swapoff -a

   
